import { generateSecureToken } from "./tokens";
import { env } from "./config";

// Module 33 Session 4B -- the deterministic outbound<->inbound correlation
// mechanism Lock #7 required. purchase_orders.negotiation_reply_token is
// plaintext (not hashed), unlike po_secure_links.token_hash -- a deliberate
// difference, not an oversight: the secure-link token is a bearer
// credential that grants portal access by itself, so it must be hashed at
// rest (sessions.refresh_token_hash's own precedent). This token grants
// nothing on its own -- it only determines WHICH PO an inbound reply
// correlates to; the real security boundary is sender verification (Lock
// #3, comparing the reply's `from` against the matched PO's own
// supplier_email_snapshot), not secrecy of this token. It must be stored
// in a directly-queryable form to look a PO up by it -- same reasoning
// staff_invites.token already uses plaintext while sessions.refresh_token_hash
// doesn't (documented precedent, CLAUDE.md's own Auth Architecture section).
export function generateReplyToken(): string {
  return generateSecureToken(24);
}

// Only a hex-token local part is ever generated by buildReplyToAddress, but
// parsing is intentionally lenient about the token's exact length/charset
// beyond "hex" -- future-proofs against generateReplyToken's own byte count
// ever changing without this parser needing a matching change.
const REPLY_ADDRESS_PATTERN = /^po-([a-f0-9]+)@/i;

// Returns null when RESEND_INBOUND_DOMAIN isn't configured -- outbound
// negotiation emails simply omit a dedicated reply-to in that case (the
// existing DEFAULT_REPLY_TO / no-replyTo-at-all fallback still applies),
// never a hard failure. This is what makes going from Resend's sandbox
// address to a real domain later a pure config change: nothing here
// hardcodes "resend.app" or any other specific domain.
export function buildReplyToAddress(replyToken: string): string | null {
  if (!env.RESEND_INBOUND_DOMAIN) return null;
  return `po-${replyToken}@${env.RESEND_INBOUND_DOMAIN}`;
}

// Extracts the correlation token from an inbound email's own `to`/
// `received_for` address (e.g. "po-<token>@<inbound-domain>" -> "<token>").
// Returns null for anything that doesn't match the expected shape --
// callers treat that identically to "no match found" (Lock #2: subject is
// never sufficient, and an address that doesn't even look like one of ours
// is not supporting evidence for anything).
export function parseReplyToken(toAddress: string): string | null {
  const match = toAddress.match(REPLY_ADDRESS_PATTERN);
  return match ? match[1] : null;
}
